---
name: Compile

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths-ignore:
      - '*.md'
      - '.git*'
  push:
    paths-ignore:
      - '*.md'
      - '.git*'

jobs:
  Compile:
    defaults:
      run:
        shell: powershell
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          path: Include/EA31337-classes
          repository: EA31337/EA31337-classes
      - name: Compile indicator (MQL4)
        uses: fx31337/mql-compile-action@master
        with:
          path: Indi_TMA_True.mq4
          include: .
          mt-version: 5.0.0.2361
          verbose: true
      - name: Compile indicator (MQL5)
        if: false
        uses: fx31337/mql-compile-action@master
        with:
          path: Indi_TMA_True.mq5
          include: .
          mt-version: 5.0.0.2515
          verbose: true
      - name: Compile strategy (MQL4)
        uses: fx31337/mql-compile-action@master
        with:
          path: Stg_TMA_True.mq4
          include: .
          mt-version: 5.0.0.2361
          verbose: true
      - name: Compile strategy (MQL5)
        uses: fx31337/mql-compile-action@master
        with:
          path: Stg_TMA_True.mq5
          include: .
          mt-version: 5.0.0.2515
          verbose: true
      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'
